### ISSUE TITLE
Running "pip install -r requirements.txt" gives an error.

### ISSUE THREAD

**Issue by joman66** [torrober/vhs.py#1]
It states:
`Processing c:\ci\cffi_1613247279197\work (from -r requirements.txt (line 24))
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\ci\\cffi_1613247279197\\work'`

**Comment by torrober** [comment]
you need to remove lines 24 and 25 in order to work properly.

However the requirements file has a lot of unnecessary libraries, I will update soon.

**Comment by joman66** [comment]
I think that's best and would be appreciated. I removed all the lines with \\ci\\ and and it fails at Cobra so I have no clue how to build it further.

**Comment by torrober** [comment]
Thanks, shortly i will commit. For now just install the imported libraries, it will work flawlessly. (eel and OpenCV,  at minimum)

**Comment by torrober** [comment]
Fixed requirements.txt file, please update repo
